### ISSUE TITLE
Add better sound (Like: Adan)

### ISSUE THREAD

**Issue by rikon-rahman** [jalalmostafa/prayertimes#16]
Currently, the prayer time alert is not very good. Sometime not realizable. A better beep sound or Adan would be great. Also, a notification message is crucial.

**Comment by jalalmostafa** [comment]
Hi Thank you for feedback.
A notification message is available at every prayer time. If you are using windows then, likely It is hiding in your notification center. But it also appears if you are on Linux or Mac.

Adan sound could be an option but the extension was developed to be used in work environments, that is why I decided on an arbitrary sound. Adding an option to choose between Adan and a different notification sound could be a nice feature. Thank you.
