### ISSUE TITLE
google maps API has expired.

### ISSUE THREAD

**Issue by elesawi** [jalalmostafa/prayertimes#36]
whenever I try to edit the settings, it gives me this message. 
![image](https://github.com/jalalmostafa/prayertimes/assets/2769865/832c11d6-ed9a-457b-8a6e-42a933ef8e78)
after a few diggings I found that the reason is the google map API has expired.
can you please fix it or at least tell me how to fix it.

**Comment by jalalmostafa** [comment]
I cannot reproduce this issue.
Which version do you have? We updated the Google Maps key a while ago, if you have the older version it could be the source of the problem.

**Comment by elesawi** [comment]
I have Version 2.2.0
I can't find V 2.3.0 the latest release is 2.2.0
